fix np.bool to bool
command used: `find -iname '*.py' -exec sed -i -E 's/np\.bool([^_])/bool\1/g' {} +`

This is fixing a failure in TOAST test "test_binned (toast.tests.binned.BinnedTest)" with the following error with newer versions of Numpy:

AttributeError: module 'numpy' has no attribute 'bool'.
`np.bool` was a deprecated alias for the builtin `bool`. To avoid this error in existing code, use `bool` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.bool_` here.
The aliases was originally deprecated in NumPy 1.20; for more details and guidance see the original release note at:
    https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations