fix git checkout toast3 on Windows
Currently,

```log
error: invalid path 'src/toast/aux/benchmarks/stats.json'

error: invalid path 'src/toast/aux/weather/LMT.h5'

error: invalid path 'src/toast/aux/weather/atacama.h5'

error: invalid path 'src/toast/aux/weather/convert.py'

error: invalid path 'src/toast/aux/weather/south_pole.h5'
```

Because AUX is reserved in Windows.

This PR propose replacing aux by _aux using the following code:

```bash
FROM=aux
TO=_aux
sed -i "s/$FROM/$TO/" src/toast/CMakeLists.txt
find src/toast -name '*.py' -exec sed -i "s/\"$FROM\"/\"$TO\"/" {} +
git mv "./src/toast/$FROM" "./src/toast/$TO"
```